/* eslint global-require: 'off' */

if (!process.browser && process.env.MOCHIFY !== 'true') {
	require('yamlify/register');
}

module.exports = [
	require('./wire01.yml'),
	require('./calc01.yml'),
	require('./calc02.yml'),
	require('./calc03.js'),
	require('./calc04.yml'),
	require('./calc05.yml'),
	require('./calc06.yml'),
	require('./make-minus-one-easy.yml'),
	require('./division-easy.yml'),
	require('./sixth-power.yml'),
	require('./remainder.yml'),
	require('./plus-32.yml'),
	require('./conditional01.js'),
	require('./conditional02.js'),
	require('./conditional03.js'),
	require('./factorial.js'),
	require('./parity.js'),
	require('./fibonacci.js'),
	require('./bivariation01.yml'),
	require('./power-easy.yml'),
	require('./power-hard.js'),
	require('./division-hard.yml'),
	require('./gcd.js'),
	require('./lcm.js'),
	require('./make-minus-one-med.yml'),
	require('./make-minus-one-hard.yml'),
	require('./sqrt-easy.js'),
	require('./sqrt-hard.js'),
	require('./complement-of-2.yml'),
	require('./binarian-easy.yml'),
	require('./perfect-number.yml'),
	require('./reversal.yml'),
	require('./msd.js'),
	require('./mod3-hard.js'),
	require('./max.yml'),
	require('./the-fifth-max.yml'),
	require('./100.yml'),
	require('./100-again.yml'),
	require('./1000.yml'),
	require('./plus-32-hard.yml'),
	require('./xor.yml'),
	require('./2017.js'),
];
