/* eslint global-require: 'off' */

if (!process.browser && process.env.MOCHIFY !== 'true') {
	require('yamlify/register');
}

module.exports = [
	require('./wire01.json'),
	require('./calc01.json'),
	require('./calc02.json'),
	require('./calc03.js'),
	require('./calc04.json'),
	require('./calc05.json'),
	require('./calc06.json'),
	require('./make-minus-one-easy.json'),
	require('./division-easy.json'),
	require('./sixth-power.json'),
	require('./remainder.json'),
	require('./plus-32.json'),
	require('./conditional01.js'),
	require('./conditional02.js'),
	require('./conditional03.js'),
	require('./factorial.js'),
	require('./parity.js'),
	require('./fibonacci.js'),
	require('./bivariation01.json'),
	require('./power-easy.json'),
	require('./power-hard.js'),
	require('./division-hard.json'),
	require('./gcd.js'),
	require('./lcm.js'),
	require('./make-minus-one-med.json'),
	require('./make-minus-one-hard.json'),
	require('./sqrt-easy.js'),
	require('./sqrt-hard.js'),
	require('./complement-of-2.json'),
	require('./binarian-easy.json'),
	require('./perfect-number.json'),
	require('./reversal.json'),
	require('./msd.js'),
	require('./mod3-hard.js'),
	require('./max.json'),
	require('./the-fifth-max.json'),
	require('./100.json'),
	require('./100-again.json'),
	require('./1000.json'),
	require('./plus-32-hard.json'),
	require('./xor.json'),
	require('./2017.js'),
];
